# ==========================================
# Runtime configuration (streaming pipeline)
# ==========================================


downscale: 1.0                # downscaling to half resolution


sensor:
  type: particles          # other options: particles | particles_layered | ... ...

# Photometric compensation: baseline | per_frame | skip
compensation_mode: skip

# Color unmixing: kmeans | skip
unmix:
  mode: skip


# ---------- DEBUG DISPLAY (OpenCV windows) ----------
display:
  enable: false

  window_scale: 1.0
  wait_key_ms: 1
  
  show_input: true

  show_flow_color_raw: true
  show_flow_quiver_raw: true

