# ==========================================
# Runtime configuration (streaming pipeline)
# ==========================================


sensor:
  type: gelsight     # other options: particles | particles_layered | ... ...
  params:
    nx: 40
    ny: 30
    dot_thresh: 40
    min_area: 5
    max_area: 60

# ---------- DEBUG DISPLAY (OpenCV windows) ----------
display:
  enable: false
  window_scale: 1.0
  wait_key_ms: 1
  
  show_input: true
  
  show_flow_color_raw: true
  show_flow_quiver_raw: true


  