# -----------------------------------------------------------------------------
# SPDX-License-Identifier: LicenseRef-YF-Research-NC-1.0
# Copyright (c) 2025 Yue Fei <feiyuefy@gmail.com>
#
# Licensed for academic research and non-commercial use only.
# Any Commercial Use (including production use or any use for commercial
# advantage) requires a separate written license from the copyright holder.
# See LICENSE-SRC-RESEARCH-NC for definitions and terms.
#
# Patent Notice:
#   No patent license is granted or implied. Users are responsible for
#   third-party patent clearance.
#
# Citation:
#   Please cite associated publications when available.
# -----------------------------------------------------------------------------


"""
Renderer of Particle-based Vision Tactile Sensor

implemented as a plugin.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Tuple
import numpy as np

from ..base import FEMOutputs, FrameBundle, Scene, SensorRenderer
from ..registry import register_sensor

# synth stack
from synth.camera import PinholeCamera
from synth.particles import LayerSpec, generate_particles
from synth.deform import DeformField
from synth.raster_cv import render_frame_cv

log = logging.getLogger(__name__)


def _parse_layers(layer_cfgs: List[Dict[str, Any]]) -> List[LayerSpec]:
    """Translate YAML layer blocks into LayerSpec objects (same as your script)."""
    out: List[LayerSpec] = []
    for L in layer_cfgs:
        out.append(
            LayerSpec(
                name=str(L["name"]),
                z_min_mm=float(L["z_mm"][0]),
                z_max_mm=float(L["z_mm"][1]),
                color_bgr=tuple(int(c) for c in L["color_bgr"]),
                density_per_mm2=float(L["density_per_mm2"]),
                radius_mm=float(L["radius_mm"]),
                depth_atten=L.get("depth_brightness", "exp"),
                depth_beta=float(L.get("depth_beta", 0.2)),
                shape=L.get("shape", "disk"),
                poly_verts=int(L.get("poly_vertices", 0)),
            )
        )
    return out


def _build_camera_from_cfg(cam_cfg: Dict[str, Any], view_mm: Tuple[float, float]) -> PinholeCamera:
    """Construct the exact same PinholeCamera as in the script."""
    img_w, img_h = int(cam_cfg["img_wh"][0]), int(cam_cfg["img_wh"][1])
    Lx_mm, Ly_mm = float(view_mm[0]), float(view_mm[1])
    Z_ref_mm = float(cam_cfg.get("z_ref_mm", 5.0))
    z_cam_mm = float(cam_cfg.get("z_cam_mm", 5.0))
    return PinholeCamera.from_viewbox(img_w, img_h, Lx_mm, Ly_mm, Z_ref_mm, z_cam_mm)


def _build_deform_field_from_cfg(def_cfg: Dict[str, Any]) -> DeformField:
    """Create a DeformField exactly as in the script."""
    mode = str(def_cfg.get("mode", "none"))
    xdmf_path = def_cfg.get("xdmf_path")
    field = DeformField(mode=mode, xdmf_path=xdmf_path)
    if field.mode == "xdmf":
        field.load()
    return field


@register_sensor("particle_vts")
class ParticleVTSRenderer(SensorRenderer):
    """
    Particle-based Vision Tactile Sensor renderer (VTS), implemented as a plugin.

    This renderer mirrors `scripts/render_camera_frame.py`:
      - Uses YAML config files for: camera/view_mm/background_bgr/layers/deformation
      - Generates random particles, samples XDMF deformation, renders via OpenCV
      - Saves BGR images (OpenCV convention)

    Notes
    -----
    - Flow is NOT generated by default.
      can add an flag later, cfg['generate_flow']=true
    - If Scene.camera is provided, it will be used; otherwise the camera is built
      from cfg['camera'] and cfg['view_mm'].
    """

    def name(self) -> str:
        return "particle_vts"

    def version(self) -> str:
        return "0.1.0"

    def modalities(self) -> Dict[str, str]:
        # Be explicit that this is BGR to match OpenCV.
        return {
            "image_bgr": "HxWx3 uint8 (OpenCV BGR)",
            # Optional future additions:
            # "flow_dense": "H×W×2 float32",
        }

    def render_frame(self, fem: FEMOutputs, scene: Scene) -> FrameBundle:
        """
        Render a single frame.

        Expected cfg keys in self.cfg:
            camera: {...}         # same as renderer.yaml: camera.*
            view_mm: [Lx, Ly]
            background_bgr: [B,G,R]  (optional; default [0,0,0])
            layers: [ ... ]       # list of layer dicts (see renderer.yaml)
            deformation: {...}    # {mode: "none"|"xdmf", xdmf_path: "..."} (optional)
            supersample: int      # optional (default 2)
            seed: int             # optional RNG seed (default 0)
        """
        cfg = dict(self.cfg or {})

        # --- Camera & viewbox ---
        cam: Optional[Any] = getattr(scene, "camera", None)
        view_wh_mm = cfg.get("view_mm", [40.0, 30.0])
        Lx_mm, Ly_mm = float(view_wh_mm[0]), float(view_wh_mm[1])

        if cam is None:
            cam_cfg = cfg.get("camera", {})
            if not cam_cfg:
                raise ValueError("Missing 'camera' config and Scene.camera is None.")
            cam = _build_camera_from_cfg(cam_cfg, (Lx_mm, Ly_mm))

        # --- Background color (BGR) ---
        bg_bgr = tuple(int(c) for c in cfg.get("background_bgr", [0, 0, 0]))

        # --- Layers ---
        layer_cfgs = cfg.get("layers", [])
        if not layer_cfgs:
            raise ValueError("Missing 'layers' config.")
        layers = _parse_layers(layer_cfgs)

        # --- Particles (rest state) ---
        seed = int(cfg.get("seed", 0))
        rng = np.random.default_rng(seed)
        parts = generate_particles(layers, Lx_mm, Ly_mm, rng)

        # --- Deformation (sample XDMF like the script) ---
        def_cfg = cfg.get("deformation", {"mode": "none"})
        field = _build_deform_field_from_cfg(def_cfg)

        if parts.xyz_mm.shape[0] > 0 and field.mode != "none":
            disp = field.sample(parts.xyz_mm)     # (N,3) displacement in mm
            parts.xyz_mm = parts.xyz_mm + disp    # apply deformation

        # --- Render (OpenCV) ---
        supersample = int(cfg.get("supersample", 2))
        img_bgr = render_frame_cv(
            cam, parts, layers, Lx_mm, Ly_mm,
            supersample=supersample, bg_color=bg_bgr
        )

        # Package outputs (mirror script behavior)
        modalities: Dict[str, Any] = {"image_bgr": img_bgr}
        meta = {
            "renderer": self.name(),
            "version": self.version(),
            "image_size": (int(img_bgr.shape[1]), int(img_bgr.shape[0])),
            "num_particles": int(parts.xyz_mm.shape[0]),
            "seed": seed,
        }
        aux = {}  # keep empty for now; we can add uv_rest/uv_def later if needed

        return FrameBundle(modalities=modalities, metadata=meta, aux=aux)
